---
- name: Land env file
  template:
    src: gunicorn.env.j2
    dest: "{{api_dir}}/gunicorn.env"
    owner: ec2-user
    group: ec2-user

- name: Start gunicorn
  shell: source gunicorn.env.j2; /usr/local/bin/gunicorn -c api/gunicorn.conf.py api:app
  args:
    chdir: "{{api_dir}}"
