---
- name: Land env file
  template:
    src: gunicorn.env.j2
    dest: "{{api_dir}}/gunicorn.env"
    owner: ec2-user
    group: ec2-user

- name: Start gunicorn
  shell: source {{api_dir}}/gunicorn.env; /usr/local/bin/gunicorn -c {{api_dir}}/api/gunicorn.conf.py api:app

- name: Autostart gunicorn on boot
  cron:
    job: source {{api_dir}}/gunicorn.env; /usr/local/bin/gunicorn -c {{api_dir}}/api/gunicorn.conf.py api:app
    user: ec2-user
    special_time: reboot
