---
- name: Land env file
  template:
    src: gunicorn.env.j2
    dest: "{{api_dir}}/gunicorn.env"
    owner: ec2-user
    group: ec2-user

- name: Land start script
  template:
    src: start-api.sh.j2
    dest: "{{api_dir}}/start-api.sh"
    owner: ec2-user
    group: ec2-user
    mode: 0755

- name: Start gunicorn
  command: "{{api_dir}}/start-api.sh" 
  args:
    chdir: "{{api_dir}}"
  become: true
  become_user: ec2-user

- name: Autostart gunicorn on boot
  cron:
    job: "{{api_dir}}/start-api.sh"
    user: ec2-user
    special_time: reboot
