---
- name: Fetch API server code
  git:
    repo: https://github.com/Calligre/server.git
    clone: yes
    depth: 1
    force: yes
    dest: "{{api_dir}}"

- name: Reset permissions on server code
  file:
    path: "{{api_dir}}"
    state: directory
    owner: ec2-user
    group: ec2-user
    recurse: true

- name: Install Python API dependencies
  pip:
    requirements: "{{ api_dir }}/api/requirements.txt"
    state: latest
    executable: pip-3.5

- name: Fetch web files
  command: aws s3 sync s3://{{web_content_bucket}} {{web_dir}}
