---
- name: Install python Packages
  pip:
    name: psycopg2
    state: latest

- name: Create unpriviliged postgres user
  postgresql_user:
    login_host: "{{db_host}}"
    port: "{{db_port}}"
    login_user: "{{db_admin_user}}"
    login_password: "{{db_admin_password}}"
    name: "{{db_user}}"
    password: "{{db_password}}"
    db: postgres # connect to the default postgres database

- name: Create Calligre database
  postgresql_db:
    login_host: "{{db_host}}"
    port: "{{db_port}}"
    login_user: "{{db_admin_user}}"
    login_password: "{{db_admin_password}}"
    name: "{{db_base}}"
    owner: "{{db_user}}"

- name: Create tables
  shell: PGPASSWORD={{db_password}} /usr/bin/psql -h {{db_host}} -p {{db_port}} -U {{db_user}} {{db_base}} -f {{api_dir}}/database/structure.up.sql
